var lakerscatApp = angular.module('lakerscatApp', []);

lakerscatApp.controller('lakersListCtrl', function ($scope) {
  $scope.players = [
    {'name': 'Brandon Bass',
     'number': 2,
     'position': 'PF', 'age': 30},
    {'name': 'Tarik Black',
     'number': 28,
     'position': 'C', 'age': 23},
    {'name': 'Vander Blue',
     'number': 12,
     'position': 'SG', 'age': 23},
     {'name': 'Anthony Brown',
     'number': 3,
     'position': 'SF', 'age': 23},
     {'name': 'Jabari Brown',
     'number': 15,
     'position': 'SG', 'age': 22},
     {'name': 'Kobe Bryant',
     'number': 24,
     'position': 'SG', 'age': 37},
     {'name': 'Jordan Clarkson',
     'number': 6,
     'position': 'PG', 'age': 23},
     {'name': 'Michael Frazier II',
     'number': 5,
     'position': 'SG', 'age': 21},
     {'name': 'Roy Hibbert',
     'number': 17,
     'position': 'C', 'age': 28},
     {'name': 'Jonathan Holmes',
     'number': 10,
     'position': 'F', 'age': 22},
     {'name': 'Marcelo Huertas',
     'number': 9,
     'position': 'PG', 'age': 32},
     {'name': 'Ryan Kelly',
     'number': 4,
     'position': 'PF', 'age': 24},
     {'name': 'Larry Nance Jr.',
     'number': 7,
     'position': 'PF', 'age': 22},
     {'name': 'Julius Randle',
     'number': 30,
     'position': 'PF', 'age': 20},
     {'name': 'DAngelo Russel',
     'number': 1,
     'position': 'PG', 'age': 19},
     {'name': 'Robert Sacre',
     'number': 50,
     'position': 'C', 'age': 26},
     {'name': 'Robert Upshaw',
     'number': 12,
     'position': 'C', 'age': 21},
     {'name': 'Louis Williams',
     'number': 23,
     'position': 'SG', 'age': 28},
     {'name': 'Metta World Peace',
     'number': 37,
     'position': 'SF', 'age': 35},
     {'name': 'Nick Young',
     'number': 0,
     'position': 'SF', 'age': 30}
  ];

  $scope.order = 'name';

});